### ISSUE TITLE
Add SwiftLint

### ISSUE THREAD

**Issue by unnamedd** [unnamedd/swift-evolution-backend#16]
Reference:
https://github.com/realm/SwiftLint

**Comment by rolivieri** [comment]
@unnamedd I added a `.swiftlint yml` file to our repo (`develop` branch). As a starting point, I used the same `.swiftlint yml` file we used in the Kitura repo: `https://github.com/IBM-Swift/Kitura/blob/master/.swiftlint.yml`.

Since we are using `Package-Builder` to build this repo in Travis CI, we also get for free the execution of swiflint on every commit. Here's an example of the warnings that we got against this repo: `https://travis-ci.org/unnamedd/swift-evolution-backend/jobs/247578333#L773`.

Feel free to update `.swiftlint.yml` file if you would like.

**Comment by unnamedd** [comment]
Very nice @rolivieri, thank you!
